# Cleansing of US Census Data
In this project, we will be working with a series of spreadsheets obtained from the US Census Bureau.  The data will be imported from multiple spreadsheets, cleansed, and prepared for analysis and visualization using tools in Python.

## Importing Libraries and Data
First, we will import the libraries to use.  This includes Glob to assist in importing the spreadsheets, Pandas for data organization, and Numpy for analysis.

In [2]:
import pandas as pd
import numpy as np
import glob

In [3]:
# The data is spread across 10 CSV files.  We have moved the files to their own 'Data' folder and will use
# glob to iterate through them and read their contents into dataframes

path = 'Data'
files = glob.glob(path + '/*.csv')
df_list = [pd.read_csv(file) for file in files]

# Now combining the individual dataframes into one

df = pd.concat(df_list, axis = 0)

# And inspecting the first few rows and data types

print(df.head())
print(df.dtypes)

   Unnamed: 0           State  TotalPop Hispanic   White   Black Native  \
0           0    Rhode Island   1053661   13.36%  74.33%   5.68%  0.35%
1           1  South Carolina   4777576    5.06%  62.89%  28.75%  0.29%
2           2    South Dakota    843190    3.24%  82.50%   1.42%  9.42%
3           3       Tennessee   6499615    4.72%  73.49%  18.28%  0.23%
4           4           Texas  26538614   38.05%  44.69%  11.65%  0.26%

   Asian Pacific       Income            GenderPop
0  3.25%   0.04%  $59,125.27       510388M_543273F
1  1.25%   0.05%  $46,296.81     2322409M_2455167F
2  1.02%   0.04%  $51,805.41       423477M_419713F
3  1.41%   0.04%  $47,328.08     3167756M_3331859F
4  3.67%   0.07%  $55,874.52   13171316M_13367298F
Unnamed: 0     int64
State         object
TotalPop       int64
Hispanic      object
White         object
Black         object
Native        object
Asian         object
Pacific       object
Income        object
GenderPop     object
dtype: object

## Cleansing the Data
From the initial inspection of our imported data, the first things we may notice is that it is out of order and has a column named 'Unnamed: 0' which appears to be a duplicate of the indices.  We will address this by sorting on the 'State' column, removing the 'Unnamed: 0' column, and reseting the indices.

In [4]:
df = df.sort_values(by = 'State').drop(['Unnamed: 0'], axis = 1).reset_index(drop = True)
print(df.head())

        State  TotalPop Hispanic   White   Black  Native   Asian Pacific  \
0     Alabama   4830620    3.75%  61.88%  31.25%   0.45%   1.05%   0.03%
1      Alaska    733375    5.91%  60.91%   2.85%  16.39%   5.45%   1.06%
2     Arizona   6641928   29.57%  57.12%   3.85%   4.36%   2.88%   0.17%
3    Arkansas   2958208    6.22%  71.14%  18.97%   0.52%   1.14%   0.15%
4  California  38421464   37.29%  40.22%   5.68%   0.41%  13.05%   0.35%

        Income            GenderPop
0  $43,296.36     2341093M_2489527F
1  $70,354.74       384160M_349215F
2  $54,207.82     3299088M_3342840F
3  $41,935.63     1451913M_1506295F
4  $67,264.78   19087135M_19334329F

Now we can look at cleaning the values themselves.  We'll want to perform analyses on the data which would currently be prevented by the special characters such as dollar signs and percentages.  Our next step will be to remove these special characters and then convert the columns to numerics.

In [5]:
# Removing all commas, dollar signs, and percent signs using regex.

df.replace('[$%,]', '', regex = True, inplace = True)

# Converting relevant columns to numeric.

df[['Hispanic', 'White', 'Black', 'Native', 'Asian', 'Pacific', 'Income']] = \
    df[['Hispanic', 'White', 'Black', 'Native', 'Asian', 'Pacific', 'Income']].apply(pd.to_numeric)

# Converting percentages to their decimal format

df[['Hispanic', 'White', 'Black', 'Native', 'Asian', 'Pacific']] = \
    round(df[['Hispanic', 'White', 'Black', 'Native', 'Asian', 'Pacific']] / 100, 4)

print(df.dtypes)

State         object
TotalPop       int64
Hispanic     float64
White        float64
Black        float64
Native       float64
Asian        float64
Pacific      float64
Income       float64
GenderPop     object
dtype: object

One messy column remains which is 'GenderPop'.  We can see from our earlier inspection that this column contains counts of a state's population by gender combined into a single string.  To make this information useful, we'll split it into two additional columns: 'Male' and 'Female'.  These columns will contain the percentage of males and females making up the population of the state.

In [6]:
# First we remove the 'M' and 'F' indicators and split the column on the underscore.

mf_count = list(df.GenderPop.replace('[MF]', '', regex = True).str.split('_'))

# Then we create the new columns using list comprehension

df['Male'] = [i[0] for i in mf_count]
df['Female'] = [i[1] for i in mf_count]

# We can now easily convert the columns to their percentages

df.Male = round(pd.to_numeric(df.Male) / df.TotalPop, 4)
df.Female = round(pd.to_numeric(df.Female) / df.TotalPop, 4)

During this process, we may have noticed that there are several missing (NaN) values in the 'Female' column.  Since we still have the total population and the proportion of males, we can infer the values and fill in the missing fields.

In [7]:
# Infering the female population percentage by subtracting the male population percentage from 1

df.Female = df.Female.fillna(1 - df.Male)

# Now dropping the 'GenderPop' column as its information is now better represented elsewhere

df.drop('GenderPop', axis=1, inplace=True)

Now that our data is clean there is another issue we'll want to address:

In [8]:
print(df.shape)

(60, 11)

We have 60 rows in our data - it would appear we have duplicates.  We can remedy that very simply.

In [9]:
df = df.drop_duplicates().reset_index(drop = True)
print(df.shape)

(51, 11)

Our data is now clean enough for analysis and visualization.

In [10]:
df

,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income,Male,Female
0,Alabama,4830620,0.0375,0.6188,0.3125,0.0045,0.0105,0.0003,43296.36,0.4846,0.5154
1,Alaska,733375,0.0591,0.6091,0.0285,0.1639,0.0545,0.0106,70354.74,0.5238,0.4762
2,Arizona,6641928,0.2957,0.5712,0.0385,0.0436,0.0288,0.0017,54207.82,0.4967,0.5033
3,Arkansas,2958208,0.0622,0.7114,0.1897,0.0052,0.0114,0.0015,41935.63,0.4908,0.5092
4,California,38421464,0.3729,0.4022,0.0568,0.0041,0.1305,0.0035,67264.78,0.4968,0.5032
5,Colorado,5278906,0.2078,0.6990,0.0355,0.0057,0.0266,NaN,64657.80,0.5017,0.4983
6,Connecticut,3593222,0.1560,0.6768,0.1035,0.0013,0.0402,0.0002,76146.56,0.4875,0.5125
7,Delaware,926454,0.0882,0.6463,0.2074,0.0026,0.0327,NaN,61827.98,0.4840,0.5160
8,District of Columbia,647484,0.0917,0.3310,0.5178,0.0020,0.0338,0.0003,75466.36,0.4736,0.5264
9,Florida,19645772,0.2134,0.5908,0.1517,0.0021,0.0228,0.0005,50690.19,0.4887,0.5113
10,Georgia,10006693,0.0842,0.5429,0.3209,0.0019,0.0310,0.0005,50811.08,0.4880,0.5120
11,Hawaii,1406299,0.0919,0.2503,0.0205,0.0014,0.3659,0.0876,73264.43,0.5048,0.4952
12,Idaho,1616547,0.1151,0.8314,0.0057,0.0147,0.0114,0.0013,48017.32,0.5014,0.4986
13,Illinois,12873761,0.1560,0.6086,0.1711,0.0012,0.0448,0.0002,59587.05,0.4907,0.5093
14,Indiana,6568645,0.0654,0.7843,0.1119,0.0019,0.0158,0.0003,48616.23,0.4925,0.5075
15,Iowa,3093526,0.0530,0.8772,0.0326,0.0029,0.0170,0.0006,53017.75,0.4961,0.5039
16,Kansas,2892987,0.1164,0.7596,0.0657,0.0073,0.0233,NaN,53885.61,0.4977,0.5023
17,Kentucky,4397353,0.0322,0.8523,0.0827,0.0017,0.0113,0.0005,45285.80,0.4922,0.5078
18,Louisiana,4625253,0.0487,0.5498,0.3633,0.0048,0.0167,0.0004,44957.99,0.4889,0.5111
19,Maine,1329100,0.0143,0.9371,0.0113,0.0079,0.0097,0.0002,49181.97,0.4891,0.5109
20,Maryland,5930538,0.0847,0.5268,0.3068,0.0020,0.0533,0.0004,78765.40,0.4844,0.5156
21,Massachusetts,6705586,0.1146,0.7304,0.0683,0.0013,0.0584,0.0002,72838.94,0.4846,0.5154
22,Michigan,9900571,0.0463,0.7238,0.1763,0.0048,0.0242,0.0002,51201.83,0.4911,0.5089
23,Minnesota,5419171,0.0515,0.8143,0.0566,0.0107,0.0416,0.0003,62820.83,0.4968,0.5032
24,Mississippi,2988081,0.0284,0.5329,0.4149,0.0039,0.0088,0.0002,38909.92,0.4858,0.5142
25,Missouri,6045448,0.0404,0.7751,0.1412,0.0036,0.0162,0.0010,49763.99,0.4903,0.5097
26,Montana,1014699,0.0327,0.8642,0.0043,0.0706,0.0057,0.0007,47645.68,0.5028,0.4972
27,Nebraska,1869365,0.0920,0.8114,0.0496,0.0086,0.0186,0.0006,55916.47,0.4973,0.5027
28,Nevada,2798636,0.2710,0.5324,0.0774,0.0109,0.0710,0.0057,55526.53,0.5030,0.4970
29,New Hampshire,1324201,0.0332,0.9132,0.0123,0.0014,0.0219,0.0002,68728.86,0.4935,0.5065
30,New Jersey,8904413,0.1875,0.5649,0.1439,0.0012,0.0816,0.0003,76581.08,0.4877,0.5123
31,New Mexico,2084117,0.4528,0.4070,0.0176,0.0925,0.0123,0.0004,47329.97,0.4954,0.5046
32,New York,19673174,0.1724,0.5647,0.1567,0.0032,0.0790,0.0002,64290.75,0.4850,0.5150
33,North Carolina,9845333,0.0846,0.6460,0.2140,0.0109,0.0232,0.0005,49937.46,0.4871,0.5129
34,North Dakota,721640,0.0283,0.8745,0.0128,0.0565,0.0096,NaN,58188.11,0.5099,0.4901
35,Ohio,11575977,0.0367,0.7590,0.1621,0.0017,0.0162,0.0002,49655.25,0.4892,0.5108
36,Oklahoma,3849733,0.1008,0.6606,0.0831,0.0672,0.0180,0.0011,48100.85,0.4953,0.5047
37,Oregon,3939233,0.1144,0.7840,0.0173,0.0100,0.0359,0.0035,54271.90,0.4946,0.5054
38,Pennsylvania,12779559,0.0613,0.7738,0.1163,0.0012,0.0280,0.0002,56170.46,0.4887,0.5113
39,Puerto Rico,3583073,0.9889,0.0077,0.0009,0.0000,0.0008,0.0000,20720.54,0.4783,0.5217
40,Rhode Island,1053661,0.1336,0.7433,0.0568,0.0035,0.0325,0.0004,59125.27,0.4844,0.5156
41,South Carolina,4777576,0.0506,0.6289,0.2875,0.0029,0.0125,0.0005,46296.81,0.4861,0.5139
42,South Dakota,843190,0.0324,0.8250,0.0142,0.0942,0.0102,0.0004,51805.41,0.5022,0.4978
43,Tennessee,6499615,0.0472,0.7349,0.1828,0.0023,0.0141,0.0004,47328.08,0.4874,0.5126
44,Texas,26538614,0.3805,0.4469,0.1165,0.0026,0.0367,0.0007,55874.52,0.4963,0.5037
45,Utah,2903379,0.1347,0.7941,0.0102,0.0108,0.0220,0.0083,63488.92,0.5026,0.4974
46,Vermont,626604,0.0161,0.9398,0.0098,0.0030,0.0124,0.0003,55602.97,0.4925,0.5075
47,Virginia,8256630,0.0801,0.6327,0.2018,0.0021,0.0546,0.0006,72866.01,0.4918,0.5082
48,Washington,6985464,0.1114,0.7204,0.0338,0.0141,0.0702,0.0061,64493.77,0.4993,0.5007
49,West Virginia,1851420,0.0129,0.9218,0.0366,0.0015,0.0068,0.0003,41437.11,0.4935,0.5065
50,Wisconsin,5742117,0.0668,0.7986,0.0820,0.0095,0.0240,0.0002,53898.89,0.4966,0.5034